import { Inter } from "next/font/google";
import Head from "next/head";
import favicon from "./favicon.svg";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Generador de códigos QR",
  description: "Generated by create next app",
  icons:{
    icon: [
      {
        url: '/favicon.svg',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/favicon.svg',
        media: '(prefers-color-scheme: dark)',
      },
    ],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
